### ISSUE TITLE
Anthracene not indexed

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/wikipedia#19] opened 2015-03-27 13:22 UTC
There is a parsing error for

c3ccc2cc1ccccc1cc2c3

This SMILES looks however correct

With more examples, the 3 first are ok, the last fail
c1ccccc1
c12ccccc1cccc2
c1cc2ccc3cccc4c3c2c(c1)cc4
c3cc2cc1ccccc1cc2cc3

**Comment by thsa** [comment] 2015-03-27 18:33
Dear Luc,

that anthracene is not working is a shocking message. I will attend to that
immediately.

Your last example seems to be an invalid smiles: c3ccc2cccc1cccc3c12
The central carbon cannot be aromatic. This works: c3ccc2cccc1cccc3C12

Kind regards,

Thomas

On Fri, Mar 27, 2015 at 2:22 PM, lpatiny <notifications@github.com> wrote:

> There is a parsing error for
>
> c3ccc2cc1ccccc1cc2c3
>
> This SMILES looks however correct
>
> With more examples, the 2 first are ok, the 2 last fail
> c1ccccc1
> c12ccccc1cccc2
> c3cc2cc1ccccc1cc2cc3
> c3ccc2cccc1cccc3c12
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cheminfo/wikipedia/issues/19>.
>

-- 

The information of this email and in any file transmitted with it is 
strictly confidential and may be legally privileged.
It is intended solely for the addressee. If you are not the intended 
recipient, any copying, distribution or any other use of this email is 
prohibited and may be unlawful. In such case, you should please notify the 
sender immediately and destroy this email.
The content of this email is not legally binding unless confirmed by letter.
Any views expressed in this message are those of the individual sender, 
except where the message states otherwise and the sender is authorized to 
state them to be the views of the sender's company.

**Comment by targos** [comment] 2015-04-08 12:02
Fixed with 60a6c13b807e46157ce95f64f3c084e4a7e5b020 and data updated in bc177be52b203009fe23a6e9367fd3d29a730699.
Thank you Thomas!

**Closed by targos** 2015-04-08 12:02 UTC
